
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int RBRACK = 14;
  public static final int ELSE = 21;
  public static final int PLUS = 8;
  public static final int MOREEQUAL = 5;
  public static final int THEN = 20;
  public static final int WHILE = 22;
  public static final int LCURL = 15;
  public static final int DIVISION = 11;
  public static final int LBRACK = 13;
  public static final int DIFFERENT = 7;
  public static final int TRUE = 24;
  public static final int IF = 19;
  public static final int LESSEQUALS = 4;
  public static final int ID = 27;
  public static final int NUM = 30;
  public static final int DO = 23;
  public static final int TYPE = 28;
  public static final int EQUALS = 6;
  public static final int LESSTHAN = 3;
  public static final int EOF = 0;
  public static final int MORETHAN = 2;
  public static final int NEWLINE = 29;
  public static final int FALSE = 25;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int ASSIGN = 12;
  public static final int RCURL = 16;
  public static final int DECLARE = 17;
  public static final int DOOR = 26;
  public static final int MOVE = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MORETHAN",
  "LESSTHAN",
  "LESSEQUALS",
  "MOREEQUAL",
  "EQUALS",
  "DIFFERENT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "ASSIGN",
  "LBRACK",
  "RBRACK",
  "LCURL",
  "RCURL",
  "DECLARE",
  "MOVE",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "TRUE",
  "FALSE",
  "DOOR",
  "ID",
  "TYPE",
  "NEWLINE",
  "NUM"
  };
}

